version: '3'

services:
  python-test-app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    network_mode: bridge
    container_name: proyectoflask2
    image: python-test-app2
    volumes: 
      - .:/app
    environment:
       FLASK_DEBUG: development
  redis:
    image: "redis:alpine"
    network_mode: bridge
  
  #splunk-ent:
  #  image: splunk/splunk
  #  environment:
  #    SPLUNK_USER: mgarridoef@gmail.com
  #    SPLUNK_PASSWORD: '@Thumas13'
  #    SPLUNK_START_ARGS: --accept-license --no-prompt
    